### ISSUE TITLE
Authorization does not seems to be working with LcobucciFactory

### ISSUE THREAD

**Issue by zspine** [symfony/mercure#65]
Everything works fine with anonymous mode enabled, with private mode I am getting a strange authorization error from mercure hub. ' cannot unmarshal number 1689617856.599472 into Go struct field claims.exp of type int64 '

```yml
# config/packages/mercure.yaml
mercure:
    enable_profiler: '%kernel.debug%'
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_PUBLIC_URL)%'
            jwt:
                secret: '%env(MERCURE_JWT_SECRET)%'
```

```php
<?php

namespace App\Controller;

use App\Mercure\Authorization;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Cookie;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mercure\Discovery;
use Symfony\Component\Routing\Annotation\Route;

class DiscoverController extends AbstractController
{
    /**
     * @Route("/discover/publish")
     */
    public function publish(Request $request, Discovery $discovery, Authorization $authorization): Response
    {
        $discovery->addLink($request);

        $response = new JsonResponse([
            '@id' => '/greetings/6',
            'availability' => 'https://schema.org/InStock'
        ]);

        $response->headers->setCookie(
            $authorization->createCookie($request,  ["https://localhost/greetings/6"])
        );

        return $response;
    }
}
```
Caddy config
```
        mercure {
            transport_url {$MERCURE_TRANSPORT_URL:bolt:///data/mercure.db}
            publisher_jwt {env.MERCURE_PUBLISHER_JWT_KEY} {env.MERCURE_PUBLISHER_JWT_ALG}
            subscriber_jwt {env.MERCURE_SUBSCRIBER_JWT_KEY} {env.MERCURE_SUBSCRIBER_JWT_ALG}
            subscriptions
            {$MERCURE_EXTRA_DIRECTIVES}
        }
```

Caddy log (api platform docker)
```json
{
  "level": "info",
  "ts": 1626545861.1293569,
  "logger": "http.handlers.mercure",
  "msg": "Subscriber unauthorized",
  "subscriber": {
    "id": "urn:uuid:a4b84639-dac8-4f0f-9970-cdfa93d8affb",
    "last_event_id": "",
    "remote_addr": "172.20.0.1:36244"
  },
  "error": "unable to parse JWT: json: cannot unmarshal number 1689617856.599472 into Go struct field claims.exp of type int64"
}
```
