### ISSUE TITLE
[BUG] Conflict with lcobucci/jwt ^4.2

### ISSUE THREAD

**Issue by silverbackdan** [symfony/mercure#89]
24 days ago lcobucci/jwt updated to version 4.2
I now get `Key provided is shorter than 256 bits, only 72 bits provided` because my passphrase is "CHANGE_ME"

in `in [vendor/lcobucci/jwt/src/Token/Builder.php ](https://localhost:8443/_profiler/open?file=vendor/lcobucci/jwt/src/Token/Builder.php&line=119#line119)-> sign (line 119)`

The key is
```
Lcobucci\JWT\Signer\Key\InMemory {#7562 ▼
  -contents: "CHANGE_ME"
  -passphrase: ""
}
```

This works without errors in 4.1 though.

The key is created in the constructor of `Symfony\Component\Mercure\Jwt\LcobucciFactory`
https://github.com/symfony/mercure/blob/main/src/Jwt/LcobucciFactory.php#L60-L63

**Comment by silverbackdan** [comment]
Seems related to:
https://github.com/lcobucci/jwt/pull/835

So in the docs the default key should probably be at least 256 bits now
e.g.
```
# config/packages/mercure.yaml
mercure:
    hubs:
        default:
            url: https://mercure-hub.example.com/.well-known/mercure
            jwt:
                secret: 'my-key-that-must-be-at-least-256-bits'
                publish: ['foo', 'https://example.com/foo']
                subscribe: ['bar', 'https://example.com/bar']
                algorithm: 'hmac.sha256'
                provider: 'My\Provider'
                factory: 'My\Factory'
                value: 'my.jwt'
```

https://symfony.com/doc/current/mercure.html#configuration

Testing this config now.
